---
apiVersion: v2
name: common
description: Function library for Helm charts
type: library
version: 1.5.1
kubeVersion: ">=1.22.0-0"
keywords:
  - common
  - library
home: https://github.com/bjw-s/helm-charts/tree/main/charts/library/common
maintainers:
  - name: bjw-s
    email: me@bjw-s.dev
annotations:
  artifacthub.io/changes: |-
    - kind: fixed
      description: Ingress secret name template is evaluated before deciding whether to omit it
    - kind: changed
      description: Updated code-server image tag to v4.13.0
    - kind: changed
      description: Updated netshoot image tag to v0.11
    - kind: changed
      description: Updated gluetun image tag to v3.34.3
