---
annotations:
  artifacthub.io/changes: |-
    - kind: added
      description: docker image and chart tested, released 1.0.16
    - kind: changed
      description: common library forked and now maintained by me aswell

apiVersion: v2
appVersion: 2.5.3
dependencies:
  - name: common
    repository: https://loeken.github.io/helm-charts
    version: 1.1.4
description: heimdall - an application dashboard and launcher
engine: gotpl
home: https://github.com/loeken/helm-charts
icon: https://d33wubrfki0l68.cloudfront.net/8c14075578b2f3d5c3c7acb0b73a911c1830aec4/96df1/images/avatar.png
maintainers:
  - email: loeken@internetz.me
    name: loeken
name: heimdall
sources:
  - https://github.com/loeken/helm-charts/tree/main/charts/heimdall
type: application
version: 1.0.17