image:
  # -- image repository
  repository: linuxserver/heimdall
  # -- image tag
  tag: version-2.5.2
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- environment variables. See more environment variables in the [heimdall documentation](https://github.com/linuxserver/docker-heimdall#parameters).
# @default -- See below
env:
  # -- Set the container timezone
  TZ: UTC
  # -- Set the container user id
  PUID: "1000"
  # -- Set the container group id
  PGID: "1000"

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 80

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: false
resources:
  limits:
    cpu: "1"
    memory: 256Mi
  requests:
    cpu: "0.5"
    memory: 128Mi
