# Use Debian-based Node image
FROM node:latest@sha256:3523df9d45c0280f49f4b503c7e2d354eeab5d676017488dd082188a0f09f99a

# Set working directory
WORKDIR /app

# Install necessary dependencies
RUN apt update && apt install -y curl sudo

# Install Helm
RUN curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

# Install Renovate globally
RUN npm install -g renovate

# Verify installations
RUN renovate --version && helm version

# Copy application files
COPY . .

# Keep container running
CMD ["tail", "-f", "/dev/null"]
