# Use Debian-based Node image
FROM node:latest@sha256:ccfc02deb6abb1b70b6ef21d3d93b3f671c0de6f463ff331cf0ea0a28ad875c9

# Set working directory
WORKDIR /app

# Install necessary dependencies
RUN apt update && apt install -y curl sudo

# Install Helm
RUN curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

# Install Renovate globally
RUN npm install -g renovate

# Verify installations
RUN renovate --version && helm version

# Copy application files
COPY . .

# Keep container running
CMD ["tail", "-f", "/dev/null"]
