annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: inital release
apiVersion: v2
appVersion: 0.22.0
dependencies:
- name: common
  repository: https://bjw-s-labs.github.io/helm-charts
  version: 3.7.3
description: a helm chart to install robusta
home: https://github.com/loeken/helm-charts
icon: https://d33wubrfki0l68.cloudfront.net/8c14075578b2f3d5c3c7acb0b73a911c1830aec4/96df1/images/avatar.png
maintainers:
- email: loeken@internetz.me
  name: loeken
name: robusta
sources:
- https://github.com/loeken/helm-charts/tree/main/charts/sinusbot
type: application
version: 2.3.0
