---
apiVersion: v2
appVersion: appversion
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.1.3
description: a helm chart to install chartname
engine: gotpl
home: https://github.com/loeken/helm-charts
kubeVersion: ">=1.16.0"
maintainers:
  - email: loeken@internetz.me
    name: loeken
name: chartname
sources:
  - https://github.com/loeken/helm-charts/tree/main/charts/chartname
type: application
version: 0.0.1