---
# annotations:
#   artifacthub.io/changes: |-
#     - kind: added
#       description: docker image and chart tested, released 1.0.0
apiVersion: v2
appVersion: appversion
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 3.7.1
description: a helm chart to install chartname
engine: gotpl
home: https://github.com/loeken/helm-charts
icon: https://d33wubrfki0l68.cloudfront.net/8c14075578b2f3d5c3c7acb0b73a911c1830aec4/96df1/images/avatar.png
maintainers:
  - email: loeken@internetz.me
    name: loeken
name: chartname
sources:
  - https://github.com/loeken/helm-charts/tree/main/charts/chartname
type: application
version: 0.0.1