apiVersion: v2
name: gha-cache-server
description: ggha-cache-server
type: application
version: 1.0.0
appVersion: 1.0.0
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 3.2.1
