# global section
global:
  # we're setting a global name for this application
  fullnameOverride: gha-cache-server
# these are default settings for all pods (aka mount the secret to pull the image)
defaultPodOptions:
  imagePullSecrets:
    - name: harbor-container-registry

controllers:
  main:
    strategy: RollingUpdate
    containers:
      main:
        image:
          repository: ghcr.io/falcondev-oss/github-actions-cache-server
          tag: "latest"
          pullPolicy: Always
        env:
        env:
          - name: URL_ACCESS_TOKEN
            valueFrom:
              secretKeyRef:
                name: cache-secret
                key: cacheServerToken
          - name: API_BASE_URL
            value: "http://gha-cache-server.cache:3000/api"
        volumeMounts:
          - name: cache-data
            mountPath: /data

# create a service for kubernetes internal routing of packages to pods/containers
service:
  # name of the main service
  main:
    # by default we turn them off
    controller: main
    enabled: true
    ports:
      http:
        port: 3000

# Define the volume
volumes:
  cache-data:
    persistentVolumeClaim:
      claimName: cache-data-pvc

# Persistent Volume Claim
persistentVolumeClaims:
  - name: cache-data-pvc
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi  # Adjust the size as needed

