# global section
global:
  # we're setting a global name for this application
  fullnameOverride: gha-cache-server
# these are default settings for all pods (aka mount the secret to pull the image)
defaultPodOptions:
  imagePullSecrets:
    - name: harbor-container-registry

controllers:
  main:
    strategy: RollingUpdate
    containers:
      main:
        image:
          repository: ghcr.io/falcondev-oss/github-actions-cache-server
          tag: "latest"
          pullPolicy: Always
        env:
          - name: CACHE_SERVER_TOKEN
            valueFrom:
              secretKeyRef:
                name: gha-cache-server-secret
                key: cacheServerToken
          - name: SECRET
            valueFrom:
              secretKeyRef:
                name: gha-cache-server-secret
                key: secret
          - name: BASE_URL
            value: "http://localhost:3000"
          - name: STORAGE_DRIVER
            value: "minio"
          - name: MINIO_BUCKET
            value: "gh-actions-cache"
          - name: MINIO_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: gha-cache-server-secret
                key: minioAccessKey
          - name: MINIO_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: gha-cache-server-secret
                key: minioSecretKey
          - name: MINIO_ENDPOINT
            value: "minio"
          - name: MINIO_PORT
            value: "9000"
          - name: MINIO_USE_SSL
            value: "false"
        volumeMounts:
          - name: cache-data
            mountPath: /data

# create a service for kubernetes internal routing of packages to pods/containers
service:
  # name of the main service
  main:
    # by default we turn them off
    controller: main
    enabled: true
    ports:
      http:
        port: 3000

# Define the volume
volumes:
  cache-data:
    persistentVolumeClaim:
      claimName: cache-data-pvc

# Persistent Volume Claim
persistentVolumeClaims:
  - name: cache-data-pvc
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi  # Adjust the size as needed
