---
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: added configmap to mount config
apiVersion: v2
appVersion: 4.7.0
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.3.2
description: rtorrent-flood - flood, a beautiful web UI for various torrent clients combined with rtorrent in this chart.
engine: gotpl
home: https://github.com/loeken/helm-charts
icon: https://d33wubrfki0l68.cloudfront.net/8c14075578b2f3d5c3c7acb0b73a911c1830aec4/96df1/images/avatar.png
maintainers:
  - email: loeken@internetz.me
    name: loeken
name: rtorrent-flood
sources:
  - https://github.com/loeken/helm-charts/tree/main/charts/rtorrent-flood
  - https://github.com/loeken/docker-rtorrent-flood/blob/main/.github/workflows/release.yml
type: application
version: 1.0.12
