---
apiVersion: v2
appVersion: 4.7.0
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.1.3
description: a helm chart to install rtorrent-flood
engine: gotpl
home: https://github.com/loeken/helm-charts
kubeVersion: ">=1.16.0"
maintainers:
  - email: loeken@internetz.me
    name: loeken
name: rtorrent-flood
sources:
  - https://github.com/loeken/helm-charts/tree/main/charts/rtorrent-flood
type: application
version: 1.0.0