controllers:
  main:
    enabled: true
    type: deployment
    containers:
      main:
        image:
          # -- image repository
          repository: loeken/nzbget
          # -- image tag
          # @default -- chart.appVersion
          tag: "v25.2-ls208"
          # -- image pull policy
          pullPolicy: Always
        # -- environment variables.
        # @default -- See below
        env:
          # -- Set the container timezone
          TZ: UTC
          NZBGET_PASS:
            valueFrom:
              secretKeyRef:
                name: nzbget
                key: password
          NZBGET_USER:
            valueFrom:
              secretKeyRef:
                name: nzbget
                key: username
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: "10m"
            memory: 128Mi

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    controller: main
    ports:
      http:
        port: 6789

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: false
  media:
    enabled: false
  downloads:
    enabled: false


probes:
  startup:
    spec:
      initialDelaySeconds: 20

# change user/group ids if needed
# env:
#  - name: PUID
#    value: 568
#  - name: PGID
#    value: 568