controllers:
  main:
    enabled: true
    type: deployment
    containers:
      main:
        image:
          # -- image repository
          repository: loeken/jellyseerr
          # -- image tag
          # @default -- chart.appVersion
          tag: "2.7.3"
          # -- image pull policy
          pullPolicy: Always
        # -- environment variables.
        # @default -- See below
        env:
          # -- Set the container timezone
          TZ: UTC
          commitTag: "2.6.0"
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: "10m"
            memory: 128Mi
# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    controller: main
    ports:
      http:
        port: 5055

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: false
