annotations:
  artifacthub.io/values-schema: values.schema.json
  artifacthub.io/changes: |-
    - kind: changed
      description: updated to 2.3.0
apiVersion: v2
appVersion: 2.3.0
dependencies:
- name: common
  repository: https://bjw-s-labs.github.io/helm-charts
  version: 4.1.1
description: a helm chart to install sinusbot
home: https://github.com/loeken/helm-charts
icon: https://d33wubrfki0l68.cloudfront.net/8c14075578b2f3d5c3c7acb0b73a911c1830aec4/96df1/images/avatar.png
maintainers:
- email: loeken@internetz.me
  name: loeken
name: sinusbot
sources:
- https://github.com/loeken/helm-charts/tree/main/charts/sinusbot
type: application
version: 2.3.0
