#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml
#

# Define the main container settings
containers:
  main:
    # Override the container name
    # nameOverride: ""

    # Specify if this container depends on any other containers
    # This is used to determine the order in which the containers are rendered.
    # dependsOn: []

    image:
      # Image repository
      repository: loeken/home-assistant
      # Image tag (default is chart.appVersion)
      # tag: ""
      # Image pull policy
      pullPolicy: Always

    # Environment variables
    env:
      # Set the container timezone
      TZ: UTC

    # Security context for the container
    securityContext:
      # Privileged securityContext may be required if USB devices are accessed directly through the host machine
      # privileged: true

    # Resource requests and limits
    resources:
      limits:
        cpu: "1"
        memory: 512Mi
      requests:
        cpu: "0.5"
        memory: 256Mi

# Configures service settings for the chart
service:
  main:
    ports:
      http:
        port: 8123

# Enable and configure ingress settings for the chart
ingress:
  main:
    enabled: false

# Enable devices to be discoverable
# hostNetwork: true

# When hostNetwork is true, set dnsPolicy to ClusterFirstWithHostNet
# dnsPolicy: ClusterFirstWithHostNet

# Configure persistence settings for the chart
persistence:
  config:
    enabled: false
  # Configure a hostPathMount to mount a USB device in the container
  usb:
    enabled: false
    type: hostPath
    hostPath: /path/to/device

# Enable and configure MariaDB database subchart
mariadb:
  enabled: false
  architecture: standalone
  auth:
    database: home-assistant
    username: home-assistant
    password: home-assistant-pass
    rootPassword: home-assistantrootpass
  primary:
    persistence:
      enabled: false
      # storageClass: ""

# Enable and configure PostgreSQL database subchart
postgresql:
  enabled: false
  image:
    repository: bitnami/postgresql
    tag: 14.1.0
  auth:
    username: home-assistant
    password: home-assistant-pass
    database: home-assistant
  primary:
    persistence:
      enabled: false
      # storageClass: ""

# Enable and configure InfluxDB database subchart
influxdb:
  enabled: false
  architecture: standalone
  authEnabled: false
  database: home_assistant
  persistence:
    enabled: false
    # storageClass: ""
    # size: 8Gi

# Enable and configure metrics settings for the chart
metrics:
  enabled: false
  serviceMonitor:
    interval: 1m
    scrapeTimeout: 30s
    labels: {}
    # See https://www.home-assistant.io/docs/authentication/ for where to find
    # long-lived access token creation under your account profile, which is
    # needed to monitor Home Assistant
    # bearerTokenSecret:
    #   name: ""
    #   key: ""
  prometheusRule:
    enabled: false
    labels: {}
    # Configure additional rules for the chart
    rules: []
      # - alert: HomeAssistantAbsent
      #   annotations:
      #     description: Home Assistant has disappeared from Prometheus service discovery.
      #     summary: Home Assistant is down.
      #   expr: |
      #     absent(up{job=~".*home-assistant.*"} == 1)
      #   for: 5m
      #   labels:
      #     severity: critical

# Enable and configure addons for the chart
addons:
  # Enable and configure CodeServer for the chart
  # This allows for easy access to configuration.yaml
  codeserver:
    enabled: false
    args:
      - --auth
      - none
      - --user-data-dir
      - /data/config/.vscode
    volumeMounts:
      - name: config
        mountPath: /data/config
