#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml
#

controllers:
  main:
    enabled: true
    type: deployment
    containers:
      main:
        image:
          # -- image repository
          repository: loeken/home-assistant
          # -- image tag
          # @default -- chart.appVersion
          tag: "2025.2.5"
          # -- image pull policy
          pullPolicy: Always
        # -- environment variables.
        # @default -- See below
        env:
          # -- Set the container timezone
          TZ: UTC

# -- Configures service settings for the chart. Normally this does not need to be modified.
# @default -- See values.yaml
service:
  main:
    controller: main
    ports:
      http:
        port: 8123

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

# -- Enable and configure mariadb database subchart under this key.
#    For more options see [mariadb chart documentation](https://github.com/bitnami/charts/tree/master/bitnami/mariadb)
# @default -- See values.yaml
mariadb:
  enabled: false
postgresql:
  enabled: false
influxdb:
  enabled: false
metrics:
  enabled: false
addons:
  # -- Enable and configure codeserver for the chart.
  #    This allows for easy access to configuration.yaml
  # @default -- See values.yaml
  codeserver:
    enabled: false
