#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#
controllers:
  main:
    enabled: true
    type: deployment
    containers:
      main:
        image:
          # -- image repository
          repository: loeken/vaultwarden
          # -- image tag
          # @default -- chart.appVersion
          tag: "1.34.1-alpine"
          # -- image pull policy
          pullPolicy: Always
        # -- environment variables.
        # @default -- See below
        env:
          # -- Set the container timezone
          - name: TZ
            value: UTC
        envFrom:
        - secretRef:
            name: vaultwarden
        # default limits
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: "10m"
            memory: 128Mi
strategy:
  type: Recreate

# -- environment variables. See [image docs](https://github.com/dani-garcia/vaultwarden/blob/main/.env.template) for more details.
# @default -- See below
env:
# -- Config dir
  DATA_FOLDER: "config"

# -- Configures service settings for the chart. Normally this does not need to be modified.
# @default -- See values.yaml
service:
  main:
    controller: main
    ports:
      http:
        port: 80
        name: main
      websocket:
        enabled: true
        port: 3012
        name: main

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false
# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: false
    accessMode: ReadWriteOnce

# https://github.com/bitnami/charts/tree/master/bitnami/mariadb/#installing-the-chart
mariadb:
  enabled: false
  # primary:
  #   persistence:
  #     enabled: true
  # auth:
  #   username: "username"
  #   password: "password"
  #   database: database

# https://github.com/bitnami/charts/tree/master/bitnami/postgresql/#installing-the-chart
postgresql:
  enabled: false
  # postgresqlUsername: ""
  # postgresqlPassword: ""
  # postgresqlDatabase: ""
  # persistence:
  #   enabled: true
  #   storageClass:
  #   accessModes:
  #     - ReadWriteOnce
resources:
  limits:
    cpu: "0.5"
    memory: 256Mi
  requests:
    memory: 128Mi
