name: check last version
on:
  push:
    branches: [ main ]
  # schedule:
  # -  cron: '0 10 * * *'
    
jobs:
  check_version:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@master
        with:
          name: bjw-s/helm-charts

      - name: fail when not matching
        run: |
          ls
          echo "cat charts/library/common/Chart.yaml|grep version|cut -d' ' -f 2"