name: check last version
on:
  # push:
  #   branches: [ main ]
  schedule:
  -  cron: '0 10 * * *'
    
jobs:
  check_version:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@master
        with:
          repository: bjw-s/helm-charts
          path: bjw
      - name: extract version
        run: |
          echo "VERSION=`cat bjw/charts/library/common/Chart.yaml|grep version|cut -d' ' -f 2`" >> $GITHUB_ENV
      - name: fail when not matching
        if: env.VERSION != '1.2.0'
        run: exit 1
