name: datree
on:
  push:
    branches: [ main ]
    
env:
  DATREE_TOKEN: ${{ secrets.DATREE_TOKEN }} 

jobs:
  k8sPolicyCheck:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: ["v1.20.0", "v1.23.12"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
              
      - name: Run Datree Policy Check
        uses: datreeio/action-datree@main
        with:
          path: 'charts'
          isHelmChart: true
          cliArguments: '--schema-version ${{ matrix.version }}'

