name: datree
on:
  push:
    branches: [ main ]
    
env:
  DATREE_TOKEN: ${{ secrets.DATREE_TOKEN }} 

jobs:
  k8sPolicyCheck:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["1.20.0", "1.21.0", "1.22.0", "1.23.0","1.24.0", "1.25.0"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
              
      - name: Run Datree Policy Check
        uses: datreeio/action-datree@main
        with:
          path: 'charts'
          isHelmChart: true
          cliArguments: '--schema-version ${{ matrix.version }}'

