name: validate & release to artifacthub
on:
  push:
    branches: [ main ]
    # paths:
    #   - 'charts/**'
env:
  DATREE_TOKEN: ${{ secrets.DATREE_TOKEN }} 
jobs:
  test:
    name: validate helm
    strategy:
      matrix:
        version: ["v1.25.6"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      # - name: setup gnupg
      #   uses: olafurpg/setup-gpg@v3
      
      - name: setup helm
        uses: azure/setup-helm@v3

      - name: Configure GPG Key
        run: |
          helm package charts/vaultwarden --sign --keyring ~/.gnupg/secring.gpg --key 73927B9AD6A8E6C5386EDD2088400BB88E717C97

      - name: Verify signature
        run: |
          helm verify vaultwarden-*.tgz.asc

      # - name: Run chart-releaser
      #   uses: helm/chart-releaser-action@v1.2.1
      #   with:
      #     config: cr.yaml
      #   env:
      #     CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
