name: validate & release to artifacthub
on:
  push:
    branches: [ main ]
    # paths:
    #   - 'charts/**'
jobs:
  test:
    name: validate helm
    strategy:
      matrix:
        version: ["1.25.4"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: get changed file
        run: echo CHANGED_CHART=`git diff-tree --no-commit-id --name-only --diff-filter=ACMRT -r main -- '*Chart.yaml' | sed '$s/$//'` >> $GITHUB_ENV
        id: changed_file


  release:
    name: release helm charts
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: checkout git code
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Publish Helm charts
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: loeken
          repository: helm-charts
