name: validate & release to artifacthub
on:
  push:
    branches: [ main ]
    paths:
      - 'charts/**'
env:
  DATREE_TOKEN: ${{ secrets.DATREE_TOKEN }} 
jobs:
  test:
    name: validate helm
    strategy:
      matrix:
        version: ["1.21.13"]
        # , "1.22.16", "1.23.14","1.24.8", "1.25.4"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: get changed file
        run: |
          echo CHANGED_CHART=`git diff-tree --no-commit-id --name-only --diff-filter=ACMRT -r main -- '*Chart.yaml' | sed '$s/$//'` >> $GITHUB_ENV
          echo CHANGED_CHART_NAME=`git diff-tree --no-commit-id --name-only --diff-filter=ACMRT -r main -- '*Chart.yaml' | sed '$s/$//' |cut -d'/' -f 2 ` >> $GITHUB_ENV
        id: changed_file

      # - name: Run Datree Policy Check
      #   uses: datreeio/action-datree@main
      #   with:
      #     path: ${{ env.CHANGED_CHART }}
      #     isHelmChart: true
      #     cliArguments: '--schema-version ${{ matrix.version }}'

      # - name: Build Helm chart
      #   run: |
      #     echo ${{ env.CHANGED_CHART }}
      #     helm package charts/${{ env.CHANGED_CHART_NAME }}

      - name: Sign Helm chart
        run: |
          helm package --sign --key ${{ secrets.GPG_KEY_ID }} charts/${{ env.CHANGED_CHART_NAME }}

      - name: Publish Helm chart
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: loeken
          repository: helm-charts
          gpg_key: ${{ secrets.GPG_PRIVATE_KEY }}
