name: security checks for docker images
on:
  schedule:
  -  cron: '0 */4 * * *'
  push:
    branches: [ main ]
jobs:
  security:
    strategy:
      fail-fast: false
      matrix:
        image: ["loeken/rtorrent-flood:4.7.1", "loeken/rtorrent:v0.9.8-r15", "loeken/vaultwarden:latest", "loeken/home-assistant:latest", "loeken/plex:latest", "linuxserver/heimdall:latest", "hotio/sonarr:latest", "linuxserver/nzbget:latest"]
    runs-on: ubuntu-latest
    steps:
    - name: Run Snyk to check Docker image for vulnerabilities
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: ${{matrix.image}}

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{matrix.image}}
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'

    - name: report version missmatch
      if: always() && steps.release.outputs.value != matrix.repo.release
      uses: ravsamhq/notify-slack-action@v1
      with:
        notification_title: "release check: ${{ steps.release.outputs.value }}"
        status: "${{ job.status }}"
        footer: "failed: ${{matrix.image}}"
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
