name: Security Check snyk / trivy
on:
  schedule:
  - cron: "30 16 * * *"

jobs:
  security:
    strategy:
      matrix:
        image: ["loeken/rtorrent-flood","loeken/rtorrent","loeken/vaultwarden"]
    runs-on: ubuntu-latest
    steps:
    - name: Run Snyk to check Docker image for vulnerabilities
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: ${{matrix.image}}
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{matrix.image}}:latest
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'