name: Example workflow for Docker using Snyk 
on:
  schedule:
  - cron: "*/15 * * * *"

jobs:
  security:
    strategy:
      matrix:
        image: ["loeken/rtorrent-flood:v4.7.0","loeken/rtorrent:v0.9.8-r15"]
    runs-on: ubuntu-latest
    steps:
    - name: Run Snyk to check Docker image for vulnerabilities
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: ${{matrix.image}}